RazorPagesDemoSolution/RazorPagesDemo/Pages/ContactMe.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net;
using System.Net.Mail;

namespace RazorPagesDemo.Pages
{
    public class ContactMeModel : PageModel
    {
        private readonly IConfiguration Configuration;

        public ContactMeModel(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        [BindProperty]
        public string Name { get; set; }
        [BindProperty]
        public string Email { get; set; }
        [BindProperty]
        public string Comments { get; set; }
        [BindProperty]
        public bool SubScribe { get; set; }

        public string? InfoMessage { get; private set; }
        public string? ErrorMessage { get; private set; }

        public void OnPostSendMessage()
        { 
            if(string.IsNullOrWhiteSpace(Name))
            {
                ModelState.AddModelError(nameof(Name), "Name is required and cannot be blank.");
                ///ErrorMessage = $"Name {defaltRequired}";
            }
            else
            {
                if(Name.Length < 5)
                {
                    ModelState.AddModelError(nameof(Name), "Name must contain 5 or more.");
                }
            }
            if (string.IsNullOrWhiteSpace(Email))
            {
                ModelState.AddModelError(nameof(Email), "Email is required and cannot be blank.");
            }
            if (string.IsNullOrWhiteSpace(Comments) || Comments.Length < 10)
            {
                ModelState.AddModelError(nameof(Comments), "Comments is required and cannot be blank.");
            }
            
            if (ModelState.IsValid)
            {
                string subscribe = SubScribe ? "Yes" : "No";
                InfoMessage = $"Name: {Name} <br />" +
                             $"Email: {Email} <br />" +
                             $"Comments: {Comments} <br />" +
                             $"Subscribe to email: {subscribe} <br />";

                SmtpClient sendMailClient = new SmtpClient();
                sendMailClient.Host = Configuration["MailServerSettings:SmtpHost"];
                sendMailClient.Port = int.Parse(Configuration["MailServerSettings:Port"]);
                sendMailClient.EnableSsl = bool.Parse(Configuration["MailServerSettings:EnableSsl"]);

                NetworkCredential mailCredentials = new NetworkCredential();
                mailCredentials.UserName = Configuration["MailServerSettings:Username"];
                mailCredentials.Password = Configuration["MailServerSettings:AppPassword"];
                sendMailClient.Credentials = mailCredentials;

                string mailToAddress = Email ?? "mingr_napat@hotmail.com";
                string mailFromAddress = Configuration["MailServerSettings:Email"];

                MailMessage mailMessage = new MailMessage(mailFromAddress, mailToAddress);
                mailMessage.Subject = "[CPSC1517] New contact me form submission";
                mailMessage.Body = InfoMessage;

                try
                {
                    sendMailClient.Send(mailMessage);
                    Name = null;
                    Email = null;
                    Comments = null;
                    InfoMessage = "Your message has been sent!";
                }
                catch (Exception ex)
                {
                    ErrorMessage = $"Error sending mail with exception: {ex.Message}";
                }
            }
        }

        public void OnPostReset()
        {
            Comments = null;
        }

        public IActionResult OnPostClear()
        {
            Name = null;
            Email = null;
            Comments = null;
            SubScribe = false;
            InfoMessage = null;
            ErrorMessage = null;
            return RedirectToPage();
        }

        public void OnGet()
        {
        }
    }
}

RazorPagesDemoSolution/RazorPagesDemo/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace RazorPagesDemo.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RazorPagesDemoSolution/RazorPagesDemo/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesDemo.Models;

namespace RazorPagesDemo.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public DateTime CurrentDateTime { get; private set; } = DateTime.Now;
        public int LuckyNumber { get; private set; } = 15;

        public void OnGet()
        {
            Random random = new Random();
            LuckyNumber = random.Next(1, 51);
        }
    }
}

RazorPagesDemoSolution/RazorPagesDemo/Pages/LottoQuickPicks.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesDemo.Models;

namespace RazorPagesDemo.Pages
{
    public class LottoQuickPicksModel : PageModel
    {
        [BindProperty]
        public string? Name { get; set; }

        [BindProperty]
        public LottoType? Type { get; set; } = LottoType.Lotto649;

        [BindProperty]
        public int QuickPicks { get; set; } = 3;

        public List<int[]> QuickPicksNumbers { get; private set; } = new();

        public string? InfoMessage { get; private set; }
        public string? ErrorMessage { get; private set; }

        public void OnGet()
        {
        }

        public void OnPostGenerateNumbers()
        {
            if (string.IsNullOrWhiteSpace(Name))
            {
                ErrorMessage = "Name is required and cannot be blank.";
            }
            else
            {
                //Remove any previous QuickPicksNumbers
                QuickPicksNumbers.Clear();
                //random
                Random random = new();
                //create a new array of int for each quick pick
                for(int quickCount = 1; quickCount <= QuickPicks; quickCount++)
                {
                    //generate 6 numbers bewteen 1 and 49 for Lotto649
                    if(Type == LottoType.Lotto649)
                    {
                        int[] currentLottoQuickPicks = new int[6];
                        for(int count = 1; count <= 6; count++)
                        {
                            int randomNumber = random.Next(1, 50);
                            while (currentLottoQuickPicks.ToList().Any(x => x == randomNumber))
                            {
                                randomNumber = random.Next(1, 50);
                            }
                            currentLottoQuickPicks[count - 1] = randomNumber;
                        }
                        //sort the contents of the array
                        Array.Sort(currentLottoQuickPicks);
                        //Add the array of int to our list
                        QuickPicksNumbers.Add(currentLottoQuickPicks);
                    }
                    else
                    {
                        //generate 7 numbers bewteen 1 and 50 for LottoMax
                        if (Type == LottoType.LottoMax)
                        {

                        }
                    }
                }
                InfoMessage = $"Hello {Name}";
            }
        }

        public IActionResult OnPostClear()
        {
            Name = null;
            InfoMessage = null;
            ErrorMessage = null;  
            return RedirectToPage();
        }
    }
}

RazorPagesDemoSolution/RazorPagesDemo/Pages/MultiplicationTable.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesDemo.Models;

namespace RazorPagesDemo.Pages
{
    public class MultiplicationTableModel : PageModel
    {
        [BindProperty]
        public int DigitsVertically { get; set; } = 9;

        [BindProperty]
        public int DigitsHorizontally { get; set; } = 9;

        public TableType? TableTypeToGenerate { get; private set; }

        public void OnGet()
        {
        }

        public void OnPostMultiply()
        {
            TableTypeToGenerate = TableType.Multiplication;
        }

        public void OnPostAdd()
        {
            TableTypeToGenerate = TableType.Addition;
        }

        public void OnPostSubtract()
        {
            TableTypeToGenerate = TableType.Subtraction;
        }
    }
}

RazorPagesDemoSolution/RazorPagesDemo/Pages/NhlPlayers.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesDemo.Models;
using System.Text.Json;
using System.Xml.Linq;

namespace RazorPagesDemo.Pages
{
    public class NhlPlayersModel : PageModel
    {
        private const string CsvFilePath = @"..\RazorPagesDemo\wwwroot\data\oilerPlayers.csv";
        private const string jsonFilePath = @"..\RazorPagesDemo\wwwroot\data\jsonPlayer.json";
        public List<Player> players { get; private set; } = new List<Player>();

        public Team team { get; private set; } = new Team();

        public void OnGet()
        {
            //ReadFromCsvFile(CsvFilePath);
            ReadFromJsonFile(jsonFilePath);
        }

        public void ReadFromJsonFile(string filePath)
        {
            try
            {
                string jsonString = System.IO.File.ReadAllText(filePath);
                JsonSerializerOptions options = new JsonSerializerOptions
                {
                    WriteIndented = true,
                    IncludeFields = true,
                };
                team = JsonSerializer.Deserialize<Team>(jsonString, options);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error serializing to Json file with exception: {ex.Message}");
            }
        }

        public void ReadFromCsvFile(string filePath)
        {
            string[] lineArray = System.IO.File.ReadAllLines(CsvFilePath);
            foreach (string line in lineArray)
            {
                try
                {
                    Player currentPlayer = new Player();
                    if (Player.TryParse(line, out currentPlayer))
                    {
                        players.Add(currentPlayer);
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Error reading file with exception {ex.Message}");
                }
            }
        }
    }
}

RazorPagesDemoSolution/RazorPagesDemo/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesDemo.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

RazorPagesDemoSolution/RazorPagesDemo/Pages/RollDice.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesDemo.Pages
{
    public class RollDiceModel : PageModel
    {
        public void OnGet()
        {
            DiceFaceImage = "/img/icons/ffffff/000000/1x1/delapouite/dice-shield.png";
        }
        
        public int DiceFaceValue { get; private set; }
        public string DiceFaceImage { get; private set; }

        public string[] DiceImage =
        {
            "/img/icons/ffffff/000000/1x1/delapouite/dice-six-faces-one.png",
            "/img/icons/ffffff/000000/1x1/delapouite/dice-six-faces-two.png",
            "/img/icons/ffffff/000000/1x1/delapouite/dice-six-faces-three.png",
            "/img/icons/ffffff/000000/1x1/delapouite/dice-six-faces-four.png",
            "/img/icons/ffffff/000000/1x1/delapouite/dice-six-faces-five.png",
            "/img/icons/ffffff/000000/1x1/delapouite/dice-six-faces-six.png"
        };
        [BindProperty]
        public int BetAmount { get; set; }
        [BindProperty]
        public int SelectedDiceSide { get; set; }
        public string? InfoMessage { get; private set; }

        public void OnPost()
        {
            Random random = new Random();
            DiceFaceValue = random.Next(1, 7);
            DiceFaceImage = DiceImage[DiceFaceValue - 1];

            if (DiceFaceValue == SelectedDiceSide)
            {
                InfoMessage = $"Congrats, you won {BetAmount:c}";
            }
            else
            {
                InfoMessage = $"I am happy but you lost {BetAmount:c}";
            }
        }
    }
}

RazorPagesDemoSolution/RazorPagesDemo/Pages/SimpleCalculator.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesDemo.Models;

namespace RazorPagesDemo.Pages
{
    public class SimpleCalculatorModel : PageModel
    {
        [BindProperty]
        public Calculator CurrentCalculator { get; set; }
        [BindProperty]
        public string? InfoMessage { get; private set; }
        [BindProperty]
        public string? ErrorMessage { get; private set; }

        public void OnPostAdd()
        {
            InfoMessage = $"{CurrentCalculator.Number1} + {CurrentCalculator.Number2} = {CurrentCalculator.Add()}";
        }
        public void OnPostSubtract()
        {
            InfoMessage = $"{CurrentCalculator.Number1} - {CurrentCalculator.Number2} = {CurrentCalculator.Subtract()}";
        }
        public void OnPostMultiply()
        {
            InfoMessage = $"{CurrentCalculator.Number1} * {CurrentCalculator.Number2} = {CurrentCalculator.Multiply()}";
        }
        public void OnPostDivide()
        {
            try
            {
                InfoMessage = $"{CurrentCalculator.Number1} / {CurrentCalculator.Number2} = {CurrentCalculator.Divide()}";
            }
            catch (Exception ex)
            {
                ErrorMessage = ex.Message;
            }
        }
        public void OnGet()
        {

        }
    }
}

RazorPagesDemoSolution/RazorPagesDemo/Pages/ContactMe.cshtml
@page
@model RazorPagesDemo.Pages.ContactMeModel
@{
}
@{
    ViewData["Title"] = "Contact Me";
}

<h1 style="background-color:maroon; color: white;">Contact Me</h1>

@if (Model.InfoMessage is not null)
{
    <div class="alert alert-info">
        @Html.Raw(Model.InfoMessage)
    </div>
}
@*@if (Model.ErrorMessage is not null)
{
    <div class="alert alert-danger">
        @Html.Raw(Model.ErrorMessage)
    </div>
}*@

<form method="post">
    <div asp-validation-summary="All" class="text-danger">
        @if(ModelState.Count > 0)
        {
            <p>Please fix the following issue(s):</p>
        }
    </div>
    <div class="row mb-3">
        <label asp-for="Name" class="col-sm-2 col-form-label">Your Name:</label>
        <div class="col-sm-10">
            <input asp-for="Name" class="form-control" />
        </div>
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="row mb-3">
        <label asp-for="Email" class="col-sm-2 col-form-label">Your Email:</label>
        <div class="col-sm-10">
            <input asp-for="Email" class="form-control" />
        </div>
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="row mb-3">
        <label asp-for="Comments" class="col-sm-2 col-form-label">Comments:</label>
        <div class="col-sm-10">
            <textarea asp-for="Comments" class="form-control"></textarea>
        </div>
        <span asp-validation-for="Comments" class="text-danger"></span>
    </div>
    <div class="row mb-3">
        <div class="col-sm-10 offset-sm-2">
            <input type="checkbox" asp-for="SubScribe" class="form-check-input" />
            <label asp-for="SubScribe" class="form-label"> SubScribe to Promotions</label>
        </div>
    </div>
    <button type="submit" asp-page-handler="SendMessage" class="btn btn-outline-success">Send Message</button>
    <button type="submit" asp-page-handler="Clear" class="btn btn-outline-secondary">Clear</button>
    <button type="submit" asp-page-handler="Reset" class="btn btn-outline-secondary">Reset</button>
</form>

RazorPagesDemoSolution/RazorPagesDemo/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>

    <h2 style="color:darksalmon">Hello World frin ASP.NET Razor Pages</h2>

    <p>The current date time is @Model.CurrentDateTime.ToString()</p>

    <div style="background-color:lightsalmon">
        <h3>@Model.LuckyNumber</h3>
    </div>

    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RazorPagesDemoSolution/RazorPagesDemo/Pages/LottoQuickPicks.cshtml
@page
@model RazorPagesDemo.Pages.LottoQuickPicksModel
@{
    ViewData["Title"] = "Lotto Quick Picks";
}

<h1 style="background-color:mediumpurple; color:white;">LottoQuickPicks</h1>
<p style="background-color:plum">This is your lucky day.
Enter your name, select a lotto type, and the number of quick picks to generate.
</p>

@if(Model.InfoMessage is not null)
{
    <div class="alert alert-info">
        @Html.Raw(Model.InfoMessage)
    </div>
}
@if (Model.ErrorMessage is not null)
{
    <div class="alert alert-danger">
        @Html.Raw(Model.ErrorMessage)
    </div>
}
@if (Model.QuickPicksNumbers.Count > 0) 
{
    int counter =1;
    @foreach (int[] currentQuickPicks in Model.QuickPicksNumbers)
    {
        <div>Quick Pick #@counter</div>
        <table>
            <tbody>
                <tr>
                    @foreach(int currentNmber in currentQuickPicks){
                        <td>@currentNmber</td>
                    }
                </tr>
            </tbody>
        </table>
        counter++;
    }
}

<form method="post">
    <div class="row mb-3">
        <label asp-for="@Model.Name" class="col-sm-2 col-form-label">Name:</label>
        <div class="col-sm-10">
            <input asp-for="@Model.Name" class="form-control" />
        </div>
    </div>
    <fieldset class="row mb-3">
        <legend class="col-form-label col-sm-2 pt-0">Lotto Type</legend>
        <div class="col-sm-10">
            <div class="form-check">
                <input asp-for="@Model.Type" class="form-check-input" type="radio" value="@Models.LottoType.Lotto649" checked>
                    @Models.LottoType.Lotto649
            </div>
            <div class="form-check">
                <input asp-for="@Model.Type" class="form-check-input" type="radio" value="@Models.LottoType.LottoMax">
                    @Models.LottoType.LottoMax
            </div>
        </div>
    </fieldset>
    <div class="row">
        <button type="submit" asp-page-handler="GenerateNumbers" class="btn btn-outline-success">Generate</button>
        <button type="submit" asp-page-handler="Clear" class="btn btn-outline-secondary">Clear</button>
    </div>
</form>

RazorPagesDemoSolution/RazorPagesDemo/Pages/MultiplicationTable.cshtml
@page
@model RazorPagesDemo.Pages.MultiplicationTableModel
@{
}

<h1> Multiplication Table </h1>

<form method="post">
    <div class="row" style="margin-bottom: 10px">
        <div class="col">
            <input asp-for="DigitsVertically" type="number" min="1" max="9" class="form-control" placeholder="digits vertically" aria-label="digits vertically"/>
        </div>
        <div class="col">
            <input asp-for="DigitsHorizontally" type="number" min="1" max="9" class="form-control" placeholder="digits horizontally" aria-label="digits horizontally" />
        </div>
    </div>
    <div class="row" style="margin-bottom: 10px">
        <button type="submit" asp-page-handler="Multiply" class="btn btn-outline-secondary"> Generate Mutiplication</button>
        <button type="submit" asp-page-handler="Add" class="btn btn-outline-success"> Generate Addition Mutiplication</button>
        <button type="submit" asp-page-handler="Subtract" class="btn btn-outline-danger"> Generate Subtraction Mutiplication</button>
    </div>
</form>

@if(Model.TableTypeToGenerate is not null)
{
    <table class="table table-bordered">
        @for(int row = 1; row <= Model.DigitsVertically; row ++)
        {
            <tr>
                @for(int col = 1; col <= Model.DigitsHorizontally; col++)
                {
                    int result = 0;
                    if (Model.TableTypeToGenerate == Models.TableType.Multiplication)
                    {
                        result = row * col;
                    }
                    else 
                    {
                        if (Model.TableTypeToGenerate == Models.TableType.Addition)
                        {
                            result = row + col;
                        }
                        else
                        {
                            if (Model.TableTypeToGenerate == Models.TableType.Subtraction)
                            {
                                result = row - col;
                            }
                        }
                    }
                    if (row == col)
                    {
                        <td style="background-color:chartreuse">
                            @result
                        </td>
                    }
                    else 
                    {
                        <td>
                            @result
                        </td>
                    }
                }
            </tr>
        }
    </table>
}

RazorPagesDemoSolution/RazorPagesDemo/Pages/NhlPlayers.cshtml
@page
@model RazorPagesDemo.Pages.NhlPlayersModel
@{
}

<h1 style="background-color:tomato">NHL Team</h1>
@if(Model.team != null)
{
    @*<table class="table table-sucess table-striped">
        <thead>
            <th>Player No</th>
            <th>Player Name</th>
            <th>Position</th>
            <th>GP</th>
            <th>Goals</th>
            <th>Assists</th>
            <th>Points</th>
        </thead>
        <tbody>
            @foreach (var currentPlayer in Model.players)
            {
                <tr>
                    <td>@currentPlayer.PlayerNo</td>
                    <td>@currentPlayer.Name</td>
                    <td>@currentPlayer.Position</td>
                    <td>@currentPlayer.GamePlayed</td>
                    <td>@currentPlayer.Goals</td>
                    <td>@currentPlayer.Assists</td>
                    <td>@currentPlayer.Points</td>
                </tr>
            }
        </tbody>
    </table>*@
    <div>Name: @Model.team.Name</div>
    <div>City: @Model.team.City</div>
    <div>Division: @Model.team.Division</div>
    <div>Conference: @Model.team.Conference</div>
    <div>Arena: @Model.team.Arena</div>
    <h4 style="background-color:tomato">NHL Player List</h4>
    <table class="table table-sucess table-striped">
        <thead>
        <th>Player No</th>
        <th>Player Name</th>
        <th>Position</th>
        <th>GP</th>
        <th>Goals</th>
        <th>Assists</th>
        <th>Points</th>
        </thead>
        <tbody>
            @foreach (var currentPlayer in Model.team.players)
            {
                <tr>
                    <td>@currentPlayer.PlayerNo</td>
                    <td>@currentPlayer.Name</td>
                    <td>@currentPlayer.Position</td>
                    <td>@currentPlayer.GamePlayed</td>
                    <td>@currentPlayer.Goals</td>
                    <td>@currentPlayer.Assists</td>
                    <td>@currentPlayer.Points</td>
                </tr>
            }
        </tbody>
    </table>
}

RazorPagesDemoSolution/RazorPagesDemo/Pages/RollDice.cshtml
@page
@model RazorPagesDemo.Pages.RollDiceModel
@{
    ViewData["Title"] = "Roll Dice";
}


<h1 style="color:cornflowerblue">Six-Sided Dice Roll Simulator</h1>
<img src="@Model.DiceFaceImage" alt="Dice Image" width="200px" height="200px"/>

@if(Model.InfoMessage != null)
{
    <div class="alert alert-info">@Model.InfoMessage</div>
}
<form method="post">
    <div>
        @*<label for="BetAmount">Bet Amount</label>
        <input type="number" min="1" max="100" id="BetAmount" name="BetAmount" value="@Model.BetAmount" />*@
        <label asp-for="BetAmount">Bet Amount</label>
        <input asp-for=BetAmount min="1" max="1000" />
    </div>
    <div>
        <label for="SelectedDiceSide">Select Dice Side</label>
        <select class="form-select" id="SelectedDiceSide" name="SelectedDiceSide">
            <option selected>Open this select menu</option>
            <option value="1">One</option>
            <option value="2">Two</option>
            <option value="3">Three</option>
            <option value="4">Four</option>
            <option value="5">Five</option>
            <option value="5">Six</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Roll Dice</button>
</form>

RazorPagesDemoSolution/RazorPagesDemo/Pages/SimpleCalculator.cshtml
@page
@model RazorPagesDemo.Pages.SimpleCalculatorModel
@{
}

<h1 style="color:palevioletred">Simple Calculator</h1>

@if(Model.InfoMessage != null)
{
    <div class="alert alert-info">
        @Model.InfoMessage
    </div>
}
@if(Model.ErrorMessage != null)
{
    <div class="alert alert-danger">
        @Model.ErrorMessage
    </div>
}

<form method="post">
    <div class="row">
        <div class="col">
            <label asp-for="CurrentCalculator.Number1">Number 1:</label>
            <input asp-for="CurrentCalculator.Number1" />
        </div>
        <div class="col">
            <label asp-for="CurrentCalculator.Number2">Number 2:</label>
            <input asp-for="CurrentCalculator.Number2" />
        </div>
    </div>
    <p></p>
    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-outline-success" asp-page-handler="Add">+</button>
        </div>
        <div class="col">
            <button type="submit" class="btn btn-outline-success" asp-page-handler="Subtract">-</button>
        </div>
        <div class="col">
            <button type="submit" class="btn btn-outline-success" asp-page-handler="Multiply">*</button>
        </div>
        <div class="col">
            <button type="submit" class="btn btn-outline-success" asp-page-handler="Divide">/</button>
        </div>
    </div>
</form>